name: Telegram Comment Notifier

on:
  issue_comment:
    types: [created, edited, deleted]
  workflow_dispatch:

jobs:
  send_msg_comment:
    name: send message if comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: send message if comment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} add comment:
            
            Comment:
            ${{ github.event.comment.body }}
            
            Comment link:
            ${{ github.event.comment.html_url }}
            
            Repository: ${{ github.repository }}