name: Merge conflicts labeler

on:
  pull_request:
  push:
    branches:
      - test
      - dev
      - main
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: set or remove
        uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
  remove_labels:
    if: contains(github.event.pull_request.labels.*.name, 'merge conflicts')
    name: remove labeles
    runs-on: ubuntu-latest
    steps:
      - name: remove teamlead label
        if: contains(github.event.pull_request.labels.*.name, 'teamlead')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: teamlead
      - name: remove review label
        if: contains(github.event.pull_request.labels.*.name, 'review')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: review
      - name: remove techlead label
        if: contains(github.event.pull_request.labels.*.name, 'techlead')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: techlead
