name: Merge conflicts labeler
on:
  push:
    branches:
      - test
      - dev
      - main
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        if: contains(github.event.pull_request.labels.*.name, 'teamlead')
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflicts"
          removeOnDirtyLabel: "teamlead"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request. <img src='https://media.giphy.com/media/0YUPDWMaHYZnIEW6Uo/giphy-downsized.gif'>"
      - name: check if prs are dirty
        if: contains(github.event.pull_request.labels.*.name, 'review')
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflicts"
          removeOnDirtyLabel: "review"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request. <img src='https://media.giphy.com/media/0YUPDWMaHYZnIEW6Uo/giphy-downsized.gif'>"
      - name: check if prs are dirty
        if: contains(github.event.pull_request.labels.*.name, 'techlead')
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "merge conflicts"
          removeOnDirtyLabel: "techlead"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request. <img src='https://media.giphy.com/media/0YUPDWMaHYZnIEW6Uo/giphy-downsized.gif'>"