name: Merge conflicts labeler

on:
  pull_request:
  push:
    branches:
      - test
      - dev
      - main
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: set or remove
        uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
